# Generated by Django 4.2.5 on 2023-12-08 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcardapp', '0003_auto_20230328_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 21, 41, 45, 611105)),
        ),
        migrations.AlterField(
            model_name='creditcardapply',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 21, 41, 45, 607116)),
        ),
        migrations.AlterField(
            model_name='creditcardapply',
            name='userimages',
            field=models.FileField(upload_to='UserImages'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 21, 41, 45, 606118)),
        ),
    ]
