# Generated by Django 4.2.5 on 2023-12-15 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcardapp', '0004_alter_contacts_created_alter_creditcardapply_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 15, 12, 2, 41, 898595)),
        ),
        migrations.AlterField(
            model_name='creditcardapply',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 15, 12, 2, 41, 896600)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 15, 12, 2, 41, 895602)),
        ),
    ]
